package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tlu20bophan generated by hbm2java
 */
public class Tlu20bophan  implements java.io.Serializable {


     private Integer id;
     private String createdBy;
     private Date createdAt;
     private boolean isActive;
     private String tenbophan;
     private String mabophan;

    public Tlu20bophan() {
    }

    public Tlu20bophan(String createdBy, Date createdAt, boolean isActive, String tenbophan, String mabophan) {
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.isActive = isActive;
       this.tenbophan = tenbophan;
       this.mabophan = mabophan;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public String getTenbophan() {
        return this.tenbophan;
    }
    
    public void setTenbophan(String tenbophan) {
        this.tenbophan = tenbophan;
    }
    public String getMabophan() {
        return this.mabophan;
    }
    
    public void setMabophan(String mabophan) {
        this.mabophan = mabophan;
    }




}


