package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tlu20trinhDoVanHoa generated by hbm2java
 */
public class Tlu20trinhDoVanHoa  implements java.io.Serializable {


     private Integer idTdvh;
     private String createdBy;
     private Date createdAt;
     private boolean isActive;
     private String tenTdvh;
     private String maTdvh;

    public Tlu20trinhDoVanHoa() {
    }

    public Tlu20trinhDoVanHoa(String createdBy, Date createdAt, boolean isActive, String tenTdvh, String maTdvh) {
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.isActive = isActive;
       this.tenTdvh = tenTdvh;
       this.maTdvh = maTdvh;
    }
   
    public Integer getIdTdvh() {
        return this.idTdvh;
    }
    
    public void setIdTdvh(Integer idTdvh) {
        this.idTdvh = idTdvh;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public String getTenTdvh() {
        return this.tenTdvh;
    }
    
    public void setTenTdvh(String tenTdvh) {
        this.tenTdvh = tenTdvh;
    }
    public String getMaTdvh() {
        return this.maTdvh;
    }
    
    public void setMaTdvh(String maTdvh) {
        this.maTdvh = maTdvh;
    }




}


