package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1



/**
 * Tlu20dangNhap generated by hbm2java
 */
public class Tlu20dangNhap  implements java.io.Serializable {


     private String username;
     private String passwords;
     private String repass;
     private String role;

    public Tlu20dangNhap() {
    }

    public Tlu20dangNhap(String username, String passwords, String repass, String role) {
       this.username = username;
       this.passwords = passwords;
       this.repass = repass;
       this.role = role;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPasswords() {
        return this.passwords;
    }
    
    public void setPasswords(String passwords) {
        this.passwords = passwords;
    }
    public String getRepass() {
        return this.repass;
    }
    
    public void setRepass(String repass) {
        this.repass = repass;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


