package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tlu20chucDanhChuyenMon generated by hbm2java
 */
public class Tlu20chucDanhChuyenMon  implements java.io.Serializable {


     private Integer idCdcm;
     private String createdBy;
     private Date createdAt;
     private boolean isActive;
     private String tenCdcm;
     private String maCdcm;

    public Tlu20chucDanhChuyenMon() {
    }

    public Tlu20chucDanhChuyenMon(String createdBy, Date createdAt, boolean isActive, String tenCdcm, String maCdcm) {
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.isActive = isActive;
       this.tenCdcm = tenCdcm;
       this.maCdcm = maCdcm;
    }
   
    public Integer getIdCdcm() {
        return this.idCdcm;
    }
    
    public void setIdCdcm(Integer idCdcm) {
        this.idCdcm = idCdcm;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public String getTenCdcm() {
        return this.tenCdcm;
    }
    
    public void setTenCdcm(String tenCdcm) {
        this.tenCdcm = tenCdcm;
    }
    public String getMaCdcm() {
        return this.maCdcm;
    }
    
    public void setMaCdcm(String maCdcm) {
        this.maCdcm = maCdcm;
    }




}


