package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tlu20dieuKienTuyenDung generated by hbm2java
 */
public class Tlu20dieuKienTuyenDung  implements java.io.Serializable {


     private Integer idDktd;
     private String createdBy;
     private Date createdAt;
     private boolean isActive;
     private String tendmdktd;
     private String madmdktd;

    public Tlu20dieuKienTuyenDung() {
    }

    public Tlu20dieuKienTuyenDung(String createdBy, Date createdAt, boolean isActive, String tendmdktd, String madmdktd) {
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.isActive = isActive;
       this.tendmdktd = tendmdktd;
       this.madmdktd = madmdktd;
    }
   
    public Integer getIdDktd() {
        return this.idDktd;
    }
    
    public void setIdDktd(Integer idDktd) {
        this.idDktd = idDktd;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public String getTendmdktd() {
        return this.tendmdktd;
    }
    
    public void setTendmdktd(String tendmdktd) {
        this.tendmdktd = tendmdktd;
    }
    public String getMadmdktd() {
        return this.madmdktd;
    }
    
    public void setMadmdktd(String madmdktd) {
        this.madmdktd = madmdktd;
    }




}


