package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tlu20thangBacLuong generated by hbm2java
 */
public class Tlu20thangBacLuong  implements java.io.Serializable {


     private Integer idTbl;
     private String createdBy;
     private Date createdAt;
     private boolean isActive;
     private String maTlb;
     private String tenTbl;
     private Date ngayHieuLuc;
     private String loaiHeSoLuong;
     private int bacLuong;
     private float heSoLuongCoBan;
     private String ghiChu;

    public Tlu20thangBacLuong() {
    }

	
    public Tlu20thangBacLuong(String createdBy, Date createdAt, boolean isActive, String maTlb, String tenTbl, Date ngayHieuLuc, String loaiHeSoLuong, int bacLuong, float heSoLuongCoBan) {
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.isActive = isActive;
        this.maTlb = maTlb;
        this.tenTbl = tenTbl;
        this.ngayHieuLuc = ngayHieuLuc;
        this.loaiHeSoLuong = loaiHeSoLuong;
        this.bacLuong = bacLuong;
        this.heSoLuongCoBan = heSoLuongCoBan;
    }
    public Tlu20thangBacLuong(String createdBy, Date createdAt, boolean isActive, String maTlb, String tenTbl, Date ngayHieuLuc, String loaiHeSoLuong, int bacLuong, float heSoLuongCoBan, String ghiChu) {
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.isActive = isActive;
       this.maTlb = maTlb;
       this.tenTbl = tenTbl;
       this.ngayHieuLuc = ngayHieuLuc;
       this.loaiHeSoLuong = loaiHeSoLuong;
       this.bacLuong = bacLuong;
       this.heSoLuongCoBan = heSoLuongCoBan;
       this.ghiChu = ghiChu;
    }
   
    public Integer getIdTbl() {
        return this.idTbl;
    }
    
    public void setIdTbl(Integer idTbl) {
        this.idTbl = idTbl;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public String getMaTlb() {
        return this.maTlb;
    }
    
    public void setMaTlb(String maTlb) {
        this.maTlb = maTlb;
    }
    public String getTenTbl() {
        return this.tenTbl;
    }
    
    public void setTenTbl(String tenTbl) {
        this.tenTbl = tenTbl;
    }
    public Date getNgayHieuLuc() {
        return this.ngayHieuLuc;
    }
    
    public void setNgayHieuLuc(Date ngayHieuLuc) {
        this.ngayHieuLuc = ngayHieuLuc;
    }
    public String getLoaiHeSoLuong() {
        return this.loaiHeSoLuong;
    }
    
    public void setLoaiHeSoLuong(String loaiHeSoLuong) {
        this.loaiHeSoLuong = loaiHeSoLuong;
    }
    public int getBacLuong() {
        return this.bacLuong;
    }
    
    public void setBacLuong(int bacLuong) {
        this.bacLuong = bacLuong;
    }
    public float getHeSoLuongCoBan() {
        return this.heSoLuongCoBan;
    }
    
    public void setHeSoLuongCoBan(float heSoLuongCoBan) {
        this.heSoLuongCoBan = heSoLuongCoBan;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }




}


