package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1



/**
 * Tlu20danhmucvongpv generated by hbm2java
 */
public class Tlu20danhmucvongpv  implements java.io.Serializable {


     private Integer id;
     private String madmvpv;
     private String tendmvpv;

    public Tlu20danhmucvongpv() {
    }

    public Tlu20danhmucvongpv(String madmvpv, String tendmvpv) {
       this.madmvpv = madmvpv;
       this.tendmvpv = tendmvpv;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMadmvpv() {
        return this.madmvpv;
    }
    
    public void setMadmvpv(String madmvpv) {
        this.madmvpv = madmvpv;
    }
    public String getTendmvpv() {
        return this.tendmvpv;
    }
    
    public void setTendmvpv(String tendmvpv) {
        this.tendmvpv = tendmvpv;
    }




}


