package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1



/**
 * Tlu30chitietdanhmucketquaphongvan generated by hbm2java
 */
public class Tlu30chitietdanhmucketquaphongvan  implements java.io.Serializable {


     private Integer id;
     private String machitietdmkqpv;
     private String mahsuv;
     private int idkqpv;

    public Tlu30chitietdanhmucketquaphongvan() {
    }

    public Tlu30chitietdanhmucketquaphongvan(String machitietdmkqpv, String mahsuv, int idkqpv) {
       this.machitietdmkqpv = machitietdmkqpv;
       this.mahsuv = mahsuv;
       this.idkqpv = idkqpv;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMachitietdmkqpv() {
        return this.machitietdmkqpv;
    }
    
    public void setMachitietdmkqpv(String machitietdmkqpv) {
        this.machitietdmkqpv = machitietdmkqpv;
    }
    public String getMahsuv() {
        return this.mahsuv;
    }
    
    public void setMahsuv(String mahsuv) {
        this.mahsuv = mahsuv;
    }
    public int getIdkqpv() {
        return this.idkqpv;
    }
    
    public void setIdkqpv(int idkqpv) {
        this.idkqpv = idkqpv;
    }




}


