package model.pojos;
// Generated Sep 14, 2015 1:42:27 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tlu30chiTietKhtd generated by hbm2java
 */
public class Tlu30chiTietKhtd  implements java.io.Serializable {


     private Integer idChiTietDktd;
     private String createdBy;
     private Date createdAt;
     private boolean isActive;
     private String maChiTietKhdt;
     private String nguoiPhongVan;
     private float diemPhongVan;
     private String nhanXet;
     private boolean dat;
     private byte trinhTrangPhongVan;
     private String ghiChu;
     private String keHoachSo;

    public Tlu30chiTietKhtd() {
    }

	
    public Tlu30chiTietKhtd(String createdBy, Date createdAt, boolean isActive, String maChiTietKhdt, String nguoiPhongVan, float diemPhongVan, String nhanXet, boolean dat, byte trinhTrangPhongVan, String keHoachSo) {
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.isActive = isActive;
        this.maChiTietKhdt = maChiTietKhdt;
        this.nguoiPhongVan = nguoiPhongVan;
        this.diemPhongVan = diemPhongVan;
        this.nhanXet = nhanXet;
        this.dat = dat;
        this.trinhTrangPhongVan = trinhTrangPhongVan;
        this.keHoachSo = keHoachSo;
    }
    public Tlu30chiTietKhtd(String createdBy, Date createdAt, boolean isActive, String maChiTietKhdt, String nguoiPhongVan, float diemPhongVan, String nhanXet, boolean dat, byte trinhTrangPhongVan, String ghiChu, String keHoachSo) {
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.isActive = isActive;
       this.maChiTietKhdt = maChiTietKhdt;
       this.nguoiPhongVan = nguoiPhongVan;
       this.diemPhongVan = diemPhongVan;
       this.nhanXet = nhanXet;
       this.dat = dat;
       this.trinhTrangPhongVan = trinhTrangPhongVan;
       this.ghiChu = ghiChu;
       this.keHoachSo = keHoachSo;
    }
   
    public Integer getIdChiTietDktd() {
        return this.idChiTietDktd;
    }
    
    public void setIdChiTietDktd(Integer idChiTietDktd) {
        this.idChiTietDktd = idChiTietDktd;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public String getMaChiTietKhdt() {
        return this.maChiTietKhdt;
    }
    
    public void setMaChiTietKhdt(String maChiTietKhdt) {
        this.maChiTietKhdt = maChiTietKhdt;
    }
    public String getNguoiPhongVan() {
        return this.nguoiPhongVan;
    }
    
    public void setNguoiPhongVan(String nguoiPhongVan) {
        this.nguoiPhongVan = nguoiPhongVan;
    }
    public float getDiemPhongVan() {
        return this.diemPhongVan;
    }
    
    public void setDiemPhongVan(float diemPhongVan) {
        this.diemPhongVan = diemPhongVan;
    }
    public String getNhanXet() {
        return this.nhanXet;
    }
    
    public void setNhanXet(String nhanXet) {
        this.nhanXet = nhanXet;
    }
    public boolean isDat() {
        return this.dat;
    }
    
    public void setDat(boolean dat) {
        this.dat = dat;
    }
    public byte getTrinhTrangPhongVan() {
        return this.trinhTrangPhongVan;
    }
    
    public void setTrinhTrangPhongVan(byte trinhTrangPhongVan) {
        this.trinhTrangPhongVan = trinhTrangPhongVan;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
    public String getKeHoachSo() {
        return this.keHoachSo;
    }
    
    public void setKeHoachSo(String keHoachSo) {
        this.keHoachSo = keHoachSo;
    }




}


