package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tlu30khaiBaoCaLamViec generated by hbm2java
 */
public class Tlu30khaiBaoCaLamViec  implements java.io.Serializable {


     private Integer idKbclv;
     private String createdBy;
     private Date createdAt;
     private boolean isActive;
     private String maKbclv;
     private String tenKbclv;
     private Date gioVaoCa;
     private Date batDauHopLeGvc;
     private Date ketThucHopLeGvc;
     private Date ketThucCa;
     private Date batDauHopLeKtc;
     private Date ketThucHopLeKtc;
     private String dienGiai;

    public Tlu30khaiBaoCaLamViec() {
    }

    public Tlu30khaiBaoCaLamViec(String createdBy, Date createdAt, boolean isActive, String maKbclv, String tenKbclv, Date gioVaoCa, Date batDauHopLeGvc, Date ketThucHopLeGvc, Date ketThucCa, Date batDauHopLeKtc, Date ketThucHopLeKtc, String dienGiai) {
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.isActive = isActive;
       this.maKbclv = maKbclv;
       this.tenKbclv = tenKbclv;
       this.gioVaoCa = gioVaoCa;
       this.batDauHopLeGvc = batDauHopLeGvc;
       this.ketThucHopLeGvc = ketThucHopLeGvc;
       this.ketThucCa = ketThucCa;
       this.batDauHopLeKtc = batDauHopLeKtc;
       this.ketThucHopLeKtc = ketThucHopLeKtc;
       this.dienGiai = dienGiai;
    }
   
    public Integer getIdKbclv() {
        return this.idKbclv;
    }
    
    public void setIdKbclv(Integer idKbclv) {
        this.idKbclv = idKbclv;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public String getMaKbclv() {
        return this.maKbclv;
    }
    
    public void setMaKbclv(String maKbclv) {
        this.maKbclv = maKbclv;
    }
    public String getTenKbclv() {
        return this.tenKbclv;
    }
    
    public void setTenKbclv(String tenKbclv) {
        this.tenKbclv = tenKbclv;
    }
    public Date getGioVaoCa() {
        return this.gioVaoCa;
    }
    
    public void setGioVaoCa(Date gioVaoCa) {
        this.gioVaoCa = gioVaoCa;
    }
    public Date getBatDauHopLeGvc() {
        return this.batDauHopLeGvc;
    }
    
    public void setBatDauHopLeGvc(Date batDauHopLeGvc) {
        this.batDauHopLeGvc = batDauHopLeGvc;
    }
    public Date getKetThucHopLeGvc() {
        return this.ketThucHopLeGvc;
    }
    
    public void setKetThucHopLeGvc(Date ketThucHopLeGvc) {
        this.ketThucHopLeGvc = ketThucHopLeGvc;
    }
    public Date getKetThucCa() {
        return this.ketThucCa;
    }
    
    public void setKetThucCa(Date ketThucCa) {
        this.ketThucCa = ketThucCa;
    }
    public Date getBatDauHopLeKtc() {
        return this.batDauHopLeKtc;
    }
    
    public void setBatDauHopLeKtc(Date batDauHopLeKtc) {
        this.batDauHopLeKtc = batDauHopLeKtc;
    }
    public Date getKetThucHopLeKtc() {
        return this.ketThucHopLeKtc;
    }
    
    public void setKetThucHopLeKtc(Date ketThucHopLeKtc) {
        this.ketThucHopLeKtc = ketThucHopLeKtc;
    }
    public String getDienGiai() {
        return this.dienGiai;
    }
    
    public void setDienGiai(String dienGiai) {
        this.dienGiai = dienGiai;
    }




}


