package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tlu30hopDongLaoDong generated by hbm2java
 */
public class Tlu30hopDongLaoDong  implements java.io.Serializable {


     private Integer idHdld;
     private String createdBy;
     private Date createdAt;
     private boolean isActive;
     private String maHdld;
     private Date ngayHdld;
     private String loaiHdld;
     private String tenNhanVien;
     private Date thoiHanBatDauHdld;
     private Date thoiHanKetThucHdld;
     private String noiLamViec;
     private String maCdcm;
     private String thoiGianLamViec;
     private String dungCuLamViec;
     private float mucLuongToiThieu;
     private float tienBhxh;
     private float tongPhuCap;
     private float luongCoBan;
     private float tongLuong;

    public Tlu30hopDongLaoDong() {
    }

	
    public Tlu30hopDongLaoDong(String createdBy, Date createdAt, boolean isActive, String maHdld, Date ngayHdld, String loaiHdld, String tenNhanVien, Date thoiHanBatDauHdld, Date thoiHanKetThucHdld, String noiLamViec, String maCdcm, float mucLuongToiThieu, float tienBhxh, float tongPhuCap, float luongCoBan, float tongLuong) {
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.isActive = isActive;
        this.maHdld = maHdld;
        this.ngayHdld = ngayHdld;
        this.loaiHdld = loaiHdld;
        this.tenNhanVien = tenNhanVien;
        this.thoiHanBatDauHdld = thoiHanBatDauHdld;
        this.thoiHanKetThucHdld = thoiHanKetThucHdld;
        this.noiLamViec = noiLamViec;
        this.maCdcm = maCdcm;
        this.mucLuongToiThieu = mucLuongToiThieu;
        this.tienBhxh = tienBhxh;
        this.tongPhuCap = tongPhuCap;
        this.luongCoBan = luongCoBan;
        this.tongLuong = tongLuong;
    }
    public Tlu30hopDongLaoDong(String createdBy, Date createdAt, boolean isActive, String maHdld, Date ngayHdld, String loaiHdld, String tenNhanVien, Date thoiHanBatDauHdld, Date thoiHanKetThucHdld, String noiLamViec, String maCdcm, String thoiGianLamViec, String dungCuLamViec, float mucLuongToiThieu, float tienBhxh, float tongPhuCap, float luongCoBan, float tongLuong) {
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.isActive = isActive;
       this.maHdld = maHdld;
       this.ngayHdld = ngayHdld;
       this.loaiHdld = loaiHdld;
       this.tenNhanVien = tenNhanVien;
       this.thoiHanBatDauHdld = thoiHanBatDauHdld;
       this.thoiHanKetThucHdld = thoiHanKetThucHdld;
       this.noiLamViec = noiLamViec;
       this.maCdcm = maCdcm;
       this.thoiGianLamViec = thoiGianLamViec;
       this.dungCuLamViec = dungCuLamViec;
       this.mucLuongToiThieu = mucLuongToiThieu;
       this.tienBhxh = tienBhxh;
       this.tongPhuCap = tongPhuCap;
       this.luongCoBan = luongCoBan;
       this.tongLuong = tongLuong;
    }
   
    public Integer getIdHdld() {
        return this.idHdld;
    }
    
    public void setIdHdld(Integer idHdld) {
        this.idHdld = idHdld;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public String getMaHdld() {
        return this.maHdld;
    }
    
    public void setMaHdld(String maHdld) {
        this.maHdld = maHdld;
    }
    public Date getNgayHdld() {
        return this.ngayHdld;
    }
    
    public void setNgayHdld(Date ngayHdld) {
        this.ngayHdld = ngayHdld;
    }
    public String getLoaiHdld() {
        return this.loaiHdld;
    }
    
    public void setLoaiHdld(String loaiHdld) {
        this.loaiHdld = loaiHdld;
    }
    public String getTenNhanVien() {
        return this.tenNhanVien;
    }
    
    public void setTenNhanVien(String tenNhanVien) {
        this.tenNhanVien = tenNhanVien;
    }
    public Date getThoiHanBatDauHdld() {
        return this.thoiHanBatDauHdld;
    }
    
    public void setThoiHanBatDauHdld(Date thoiHanBatDauHdld) {
        this.thoiHanBatDauHdld = thoiHanBatDauHdld;
    }
    public Date getThoiHanKetThucHdld() {
        return this.thoiHanKetThucHdld;
    }
    
    public void setThoiHanKetThucHdld(Date thoiHanKetThucHdld) {
        this.thoiHanKetThucHdld = thoiHanKetThucHdld;
    }
    public String getNoiLamViec() {
        return this.noiLamViec;
    }
    
    public void setNoiLamViec(String noiLamViec) {
        this.noiLamViec = noiLamViec;
    }
    public String getMaCdcm() {
        return this.maCdcm;
    }
    
    public void setMaCdcm(String maCdcm) {
        this.maCdcm = maCdcm;
    }
    public String getThoiGianLamViec() {
        return this.thoiGianLamViec;
    }
    
    public void setThoiGianLamViec(String thoiGianLamViec) {
        this.thoiGianLamViec = thoiGianLamViec;
    }
    public String getDungCuLamViec() {
        return this.dungCuLamViec;
    }
    
    public void setDungCuLamViec(String dungCuLamViec) {
        this.dungCuLamViec = dungCuLamViec;
    }
    public float getMucLuongToiThieu() {
        return this.mucLuongToiThieu;
    }
    
    public void setMucLuongToiThieu(float mucLuongToiThieu) {
        this.mucLuongToiThieu = mucLuongToiThieu;
    }
    public float getTienBhxh() {
        return this.tienBhxh;
    }
    
    public void setTienBhxh(float tienBhxh) {
        this.tienBhxh = tienBhxh;
    }
    public float getTongPhuCap() {
        return this.tongPhuCap;
    }
    
    public void setTongPhuCap(float tongPhuCap) {
        this.tongPhuCap = tongPhuCap;
    }
    public float getLuongCoBan() {
        return this.luongCoBan;
    }
    
    public void setLuongCoBan(float luongCoBan) {
        this.luongCoBan = luongCoBan;
    }
    public float getTongLuong() {
        return this.tongLuong;
    }
    
    public void setTongLuong(float tongLuong) {
        this.tongLuong = tongLuong;
    }




}


