package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tlu30keHoachDaoTao generated by hbm2java
 */
public class Tlu30keHoachDaoTao  implements java.io.Serializable {


     private Integer idKhdt;
     private String keHoachSo;
     private Date ngayKeHoach;
     private String createdBy;
     private Date createdAt;
     private boolean isActive;
     private String boPhan;
     private Date ngayBatDauKeHoach;
     private Date ngayKetThucKeHoach;
     private int soNguoi;
     private float nganSach;
     private String noiDung;

    public Tlu30keHoachDaoTao() {
    }

	
    public Tlu30keHoachDaoTao(String keHoachSo, Date ngayKeHoach, String createdBy, Date createdAt, boolean isActive, String boPhan, Date ngayBatDauKeHoach, Date ngayKetThucKeHoach, int soNguoi, float nganSach) {
        this.keHoachSo = keHoachSo;
        this.ngayKeHoach = ngayKeHoach;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.isActive = isActive;
        this.boPhan = boPhan;
        this.ngayBatDauKeHoach = ngayBatDauKeHoach;
        this.ngayKetThucKeHoach = ngayKetThucKeHoach;
        this.soNguoi = soNguoi;
        this.nganSach = nganSach;
    }
    public Tlu30keHoachDaoTao(String keHoachSo, Date ngayKeHoach, String createdBy, Date createdAt, boolean isActive, String boPhan, Date ngayBatDauKeHoach, Date ngayKetThucKeHoach, int soNguoi, float nganSach, String noiDung) {
       this.keHoachSo = keHoachSo;
       this.ngayKeHoach = ngayKeHoach;
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.isActive = isActive;
       this.boPhan = boPhan;
       this.ngayBatDauKeHoach = ngayBatDauKeHoach;
       this.ngayKetThucKeHoach = ngayKetThucKeHoach;
       this.soNguoi = soNguoi;
       this.nganSach = nganSach;
       this.noiDung = noiDung;
    }
   
    public Integer getIdKhdt() {
        return this.idKhdt;
    }
    
    public void setIdKhdt(Integer idKhdt) {
        this.idKhdt = idKhdt;
    }
    public String getKeHoachSo() {
        return this.keHoachSo;
    }
    
    public void setKeHoachSo(String keHoachSo) {
        this.keHoachSo = keHoachSo;
    }
    public Date getNgayKeHoach() {
        return this.ngayKeHoach;
    }
    
    public void setNgayKeHoach(Date ngayKeHoach) {
        this.ngayKeHoach = ngayKeHoach;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public String getBoPhan() {
        return this.boPhan;
    }
    
    public void setBoPhan(String boPhan) {
        this.boPhan = boPhan;
    }
    public Date getNgayBatDauKeHoach() {
        return this.ngayBatDauKeHoach;
    }
    
    public void setNgayBatDauKeHoach(Date ngayBatDauKeHoach) {
        this.ngayBatDauKeHoach = ngayBatDauKeHoach;
    }
    public Date getNgayKetThucKeHoach() {
        return this.ngayKetThucKeHoach;
    }
    
    public void setNgayKetThucKeHoach(Date ngayKetThucKeHoach) {
        this.ngayKetThucKeHoach = ngayKetThucKeHoach;
    }
    public int getSoNguoi() {
        return this.soNguoi;
    }
    
    public void setSoNguoi(int soNguoi) {
        this.soNguoi = soNguoi;
    }
    public float getNganSach() {
        return this.nganSach;
    }
    
    public void setNganSach(float nganSach) {
        this.nganSach = nganSach;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }




}


