package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1



/**
 * Tlu30chitietdktd generated by hbm2java
 */
public class Tlu30chitietdktd  implements java.io.Serializable {


     private Integer id;
     private String tenchitietdktd;
     private String machitietdktd;
     private String kehoachtuyendung;
     private float diemcandat;

    public Tlu30chitietdktd() {
    }

    public Tlu30chitietdktd(String tenchitietdktd, String machitietdktd, String kehoachtuyendung, float diemcandat) {
       this.tenchitietdktd = tenchitietdktd;
       this.machitietdktd = machitietdktd;
       this.kehoachtuyendung = kehoachtuyendung;
       this.diemcandat = diemcandat;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTenchitietdktd() {
        return this.tenchitietdktd;
    }
    
    public void setTenchitietdktd(String tenchitietdktd) {
        this.tenchitietdktd = tenchitietdktd;
    }
    public String getMachitietdktd() {
        return this.machitietdktd;
    }
    
    public void setMachitietdktd(String machitietdktd) {
        this.machitietdktd = machitietdktd;
    }
    public String getKehoachtuyendung() {
        return this.kehoachtuyendung;
    }
    
    public void setKehoachtuyendung(String kehoachtuyendung) {
        this.kehoachtuyendung = kehoachtuyendung;
    }
    public float getDiemcandat() {
        return this.diemcandat;
    }
    
    public void setDiemcandat(float diemcandat) {
        this.diemcandat = diemcandat;
    }




}


