package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tlu30truongDaoTao generated by hbm2java
 */
public class Tlu30truongDaoTao  implements java.io.Serializable {


     private Integer idTdt;
     private String createdBy;
     private Date createdAt;
     private boolean isActive;
     private String tenTdt;
     private String maTdt;

    public Tlu30truongDaoTao() {
    }

    public Tlu30truongDaoTao(String createdBy, Date createdAt, boolean isActive, String tenTdt, String maTdt) {
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.isActive = isActive;
       this.tenTdt = tenTdt;
       this.maTdt = maTdt;
    }
   
    public Integer getIdTdt() {
        return this.idTdt;
    }
    
    public void setIdTdt(Integer idTdt) {
        this.idTdt = idTdt;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public String getTenTdt() {
        return this.tenTdt;
    }
    
    public void setTenTdt(String tenTdt) {
        this.tenTdt = tenTdt;
    }
    public String getMaTdt() {
        return this.maTdt;
    }
    
    public void setMaTdt(String maTdt) {
        this.maTdt = maTdt;
    }




}


