package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tlu30chiTietDaoTao generated by hbm2java
 */
public class Tlu30chiTietDaoTao  implements java.io.Serializable {


     private Integer idCtdt;
     private String createdBy;
     private Date createdAt;
     private boolean isActive;
     private String keHoachSo;
     private String nhanVien;
     private String truongDaoTao;
     private String nganhDaoTao;
     private String bangDaoTao;
     private Date ngayBatDauDaoTao;
     private Date ngayKetThucDaoTao;
     private float hocPhi;
     private float kinhPhiCongTyCap;
     private float kinhPhiCaNhan;
     private String ghiChu;
     private boolean daHoanThanh;

    public Tlu30chiTietDaoTao() {
    }

	
    public Tlu30chiTietDaoTao(String createdBy, Date createdAt, boolean isActive, String keHoachSo, String nhanVien, String truongDaoTao, String nganhDaoTao, String bangDaoTao, Date ngayBatDauDaoTao, Date ngayKetThucDaoTao, float hocPhi, float kinhPhiCongTyCap, float kinhPhiCaNhan, boolean daHoanThanh) {
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.isActive = isActive;
        this.keHoachSo = keHoachSo;
        this.nhanVien = nhanVien;
        this.truongDaoTao = truongDaoTao;
        this.nganhDaoTao = nganhDaoTao;
        this.bangDaoTao = bangDaoTao;
        this.ngayBatDauDaoTao = ngayBatDauDaoTao;
        this.ngayKetThucDaoTao = ngayKetThucDaoTao;
        this.hocPhi = hocPhi;
        this.kinhPhiCongTyCap = kinhPhiCongTyCap;
        this.kinhPhiCaNhan = kinhPhiCaNhan;
        this.daHoanThanh = daHoanThanh;
    }
    public Tlu30chiTietDaoTao(String createdBy, Date createdAt, boolean isActive, String keHoachSo, String nhanVien, String truongDaoTao, String nganhDaoTao, String bangDaoTao, Date ngayBatDauDaoTao, Date ngayKetThucDaoTao, float hocPhi, float kinhPhiCongTyCap, float kinhPhiCaNhan, String ghiChu, boolean daHoanThanh) {
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.isActive = isActive;
       this.keHoachSo = keHoachSo;
       this.nhanVien = nhanVien;
       this.truongDaoTao = truongDaoTao;
       this.nganhDaoTao = nganhDaoTao;
       this.bangDaoTao = bangDaoTao;
       this.ngayBatDauDaoTao = ngayBatDauDaoTao;
       this.ngayKetThucDaoTao = ngayKetThucDaoTao;
       this.hocPhi = hocPhi;
       this.kinhPhiCongTyCap = kinhPhiCongTyCap;
       this.kinhPhiCaNhan = kinhPhiCaNhan;
       this.ghiChu = ghiChu;
       this.daHoanThanh = daHoanThanh;
    }
   
    public Integer getIdCtdt() {
        return this.idCtdt;
    }
    
    public void setIdCtdt(Integer idCtdt) {
        this.idCtdt = idCtdt;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public String getKeHoachSo() {
        return this.keHoachSo;
    }
    
    public void setKeHoachSo(String keHoachSo) {
        this.keHoachSo = keHoachSo;
    }
    public String getNhanVien() {
        return this.nhanVien;
    }
    
    public void setNhanVien(String nhanVien) {
        this.nhanVien = nhanVien;
    }
    public String getTruongDaoTao() {
        return this.truongDaoTao;
    }
    
    public void setTruongDaoTao(String truongDaoTao) {
        this.truongDaoTao = truongDaoTao;
    }
    public String getNganhDaoTao() {
        return this.nganhDaoTao;
    }
    
    public void setNganhDaoTao(String nganhDaoTao) {
        this.nganhDaoTao = nganhDaoTao;
    }
    public String getBangDaoTao() {
        return this.bangDaoTao;
    }
    
    public void setBangDaoTao(String bangDaoTao) {
        this.bangDaoTao = bangDaoTao;
    }
    public Date getNgayBatDauDaoTao() {
        return this.ngayBatDauDaoTao;
    }
    
    public void setNgayBatDauDaoTao(Date ngayBatDauDaoTao) {
        this.ngayBatDauDaoTao = ngayBatDauDaoTao;
    }
    public Date getNgayKetThucDaoTao() {
        return this.ngayKetThucDaoTao;
    }
    
    public void setNgayKetThucDaoTao(Date ngayKetThucDaoTao) {
        this.ngayKetThucDaoTao = ngayKetThucDaoTao;
    }
    public float getHocPhi() {
        return this.hocPhi;
    }
    
    public void setHocPhi(float hocPhi) {
        this.hocPhi = hocPhi;
    }
    public float getKinhPhiCongTyCap() {
        return this.kinhPhiCongTyCap;
    }
    
    public void setKinhPhiCongTyCap(float kinhPhiCongTyCap) {
        this.kinhPhiCongTyCap = kinhPhiCongTyCap;
    }
    public float getKinhPhiCaNhan() {
        return this.kinhPhiCaNhan;
    }
    
    public void setKinhPhiCaNhan(float kinhPhiCaNhan) {
        this.kinhPhiCaNhan = kinhPhiCaNhan;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
    public boolean isDaHoanThanh() {
        return this.daHoanThanh;
    }
    
    public void setDaHoanThanh(boolean daHoanThanh) {
        this.daHoanThanh = daHoanThanh;
    }




}


