package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tlu30hoSoUngVien generated by hbm2java
 */
public class Tlu30hoSoUngVien  implements java.io.Serializable {


     private Integer idHsuv;
     private String createdBy;
     private Date createdAt;
     private boolean isActive;
     private String maHoSo;
     private Date ngayNhanHoSo;
     private String keHoachSo;
     private String boPhanDuTuyen;
     private String trinhDoVanHoa;
     private String hoTen;
     private String gioiTinh;
     private int cmdn;
     private int dienThoai;
     private String email;
     private String kinhNghiem;
     private String ghiChu;
     private String kemSoYeuLyLich;
     private String kemDonXinViec;
     private String kemGiayKhamSucKhoe;
     private String kemCmdn;
     private String kemHoKhau;
     private String kemBangCap;
     private String giayToKhac;

    public Tlu30hoSoUngVien() {
    }

	
    public Tlu30hoSoUngVien(String createdBy, Date createdAt, boolean isActive, String maHoSo, Date ngayNhanHoSo, String keHoachSo, String boPhanDuTuyen, String trinhDoVanHoa, String hoTen, String gioiTinh, int cmdn, int dienThoai, String email) {
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.isActive = isActive;
        this.maHoSo = maHoSo;
        this.ngayNhanHoSo = ngayNhanHoSo;
        this.keHoachSo = keHoachSo;
        this.boPhanDuTuyen = boPhanDuTuyen;
        this.trinhDoVanHoa = trinhDoVanHoa;
        this.hoTen = hoTen;
        this.gioiTinh = gioiTinh;
        this.cmdn = cmdn;
        this.dienThoai = dienThoai;
        this.email = email;
    }
    public Tlu30hoSoUngVien(String createdBy, Date createdAt, boolean isActive, String maHoSo, Date ngayNhanHoSo, String keHoachSo, String boPhanDuTuyen, String trinhDoVanHoa, String hoTen, String gioiTinh, int cmdn, int dienThoai, String email, String kinhNghiem, String ghiChu, String kemSoYeuLyLich, String kemDonXinViec, String kemGiayKhamSucKhoe, String kemCmdn, String kemHoKhau, String kemBangCap, String giayToKhac) {
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.isActive = isActive;
       this.maHoSo = maHoSo;
       this.ngayNhanHoSo = ngayNhanHoSo;
       this.keHoachSo = keHoachSo;
       this.boPhanDuTuyen = boPhanDuTuyen;
       this.trinhDoVanHoa = trinhDoVanHoa;
       this.hoTen = hoTen;
       this.gioiTinh = gioiTinh;
       this.cmdn = cmdn;
       this.dienThoai = dienThoai;
       this.email = email;
       this.kinhNghiem = kinhNghiem;
       this.ghiChu = ghiChu;
       this.kemSoYeuLyLich = kemSoYeuLyLich;
       this.kemDonXinViec = kemDonXinViec;
       this.kemGiayKhamSucKhoe = kemGiayKhamSucKhoe;
       this.kemCmdn = kemCmdn;
       this.kemHoKhau = kemHoKhau;
       this.kemBangCap = kemBangCap;
       this.giayToKhac = giayToKhac;
    }
   
    public Integer getIdHsuv() {
        return this.idHsuv;
    }
    
    public void setIdHsuv(Integer idHsuv) {
        this.idHsuv = idHsuv;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public String getMaHoSo() {
        return this.maHoSo;
    }
    
    public void setMaHoSo(String maHoSo) {
        this.maHoSo = maHoSo;
    }
    public Date getNgayNhanHoSo() {
        return this.ngayNhanHoSo;
    }
    
    public void setNgayNhanHoSo(Date ngayNhanHoSo) {
        this.ngayNhanHoSo = ngayNhanHoSo;
    }
    public String getKeHoachSo() {
        return this.keHoachSo;
    }
    
    public void setKeHoachSo(String keHoachSo) {
        this.keHoachSo = keHoachSo;
    }
    public String getBoPhanDuTuyen() {
        return this.boPhanDuTuyen;
    }
    
    public void setBoPhanDuTuyen(String boPhanDuTuyen) {
        this.boPhanDuTuyen = boPhanDuTuyen;
    }
    public String getTrinhDoVanHoa() {
        return this.trinhDoVanHoa;
    }
    
    public void setTrinhDoVanHoa(String trinhDoVanHoa) {
        this.trinhDoVanHoa = trinhDoVanHoa;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public int getCmdn() {
        return this.cmdn;
    }
    
    public void setCmdn(int cmdn) {
        this.cmdn = cmdn;
    }
    public int getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(int dienThoai) {
        this.dienThoai = dienThoai;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getKinhNghiem() {
        return this.kinhNghiem;
    }
    
    public void setKinhNghiem(String kinhNghiem) {
        this.kinhNghiem = kinhNghiem;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
    public String getKemSoYeuLyLich() {
        return this.kemSoYeuLyLich;
    }
    
    public void setKemSoYeuLyLich(String kemSoYeuLyLich) {
        this.kemSoYeuLyLich = kemSoYeuLyLich;
    }
    public String getKemDonXinViec() {
        return this.kemDonXinViec;
    }
    
    public void setKemDonXinViec(String kemDonXinViec) {
        this.kemDonXinViec = kemDonXinViec;
    }
    public String getKemGiayKhamSucKhoe() {
        return this.kemGiayKhamSucKhoe;
    }
    
    public void setKemGiayKhamSucKhoe(String kemGiayKhamSucKhoe) {
        this.kemGiayKhamSucKhoe = kemGiayKhamSucKhoe;
    }
    public String getKemCmdn() {
        return this.kemCmdn;
    }
    
    public void setKemCmdn(String kemCmdn) {
        this.kemCmdn = kemCmdn;
    }
    public String getKemHoKhau() {
        return this.kemHoKhau;
    }
    
    public void setKemHoKhau(String kemHoKhau) {
        this.kemHoKhau = kemHoKhau;
    }
    public String getKemBangCap() {
        return this.kemBangCap;
    }
    
    public void setKemBangCap(String kemBangCap) {
        this.kemBangCap = kemBangCap;
    }
    public String getGiayToKhac() {
        return this.giayToKhac;
    }
    
    public void setGiayToKhac(String giayToKhac) {
        this.giayToKhac = giayToKhac;
    }




}


