package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1



/**
 * Tlu30chitietvpv generated by hbm2java
 */
public class Tlu30chitietvpv  implements java.io.Serializable {


     private Integer id;
     private String machitietvpv;
     private String madmvpv;
     private int soLichPhongVan;

    public Tlu30chitietvpv() {
    }

    public Tlu30chitietvpv(String machitietvpv, String madmvpv, int soLichPhongVan) {
       this.machitietvpv = machitietvpv;
       this.madmvpv = madmvpv;
       this.soLichPhongVan = soLichPhongVan;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMachitietvpv() {
        return this.machitietvpv;
    }
    
    public void setMachitietvpv(String machitietvpv) {
        this.machitietvpv = machitietvpv;
    }
    public String getMadmvpv() {
        return this.madmvpv;
    }
    
    public void setMadmvpv(String madmvpv) {
        this.madmvpv = madmvpv;
    }
    public int getSoLichPhongVan() {
        return this.soLichPhongVan;
    }
    
    public void setSoLichPhongVan(int soLichPhongVan) {
        this.soLichPhongVan = soLichPhongVan;
    }




}


