package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tlu30ketQuaPhongVan generated by hbm2java
 */
public class Tlu30ketQuaPhongVan  implements java.io.Serializable {


     private Integer idKqpv;
     private String createdBy;
     private Date createdAt;
     private boolean isActive;
     private String nguoiPhongVan;
     private String nhanXet;
     private boolean datYeuCau;
     private boolean tinhTrangPhongVan;
     private String ghiChu;
     private String keHoachSo;
     private String machitietvpv;

    public Tlu30ketQuaPhongVan() {
    }

	
    public Tlu30ketQuaPhongVan(String createdBy, Date createdAt, boolean isActive, String nguoiPhongVan, String nhanXet, boolean datYeuCau, boolean tinhTrangPhongVan, String keHoachSo, String machitietvpv) {
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.isActive = isActive;
        this.nguoiPhongVan = nguoiPhongVan;
        this.nhanXet = nhanXet;
        this.datYeuCau = datYeuCau;
        this.tinhTrangPhongVan = tinhTrangPhongVan;
        this.keHoachSo = keHoachSo;
        this.machitietvpv = machitietvpv;
    }
    public Tlu30ketQuaPhongVan(String createdBy, Date createdAt, boolean isActive, String nguoiPhongVan, String nhanXet, boolean datYeuCau, boolean tinhTrangPhongVan, String ghiChu, String keHoachSo, String machitietvpv) {
       this.createdBy = createdBy;
       this.createdAt = createdAt;
       this.isActive = isActive;
       this.nguoiPhongVan = nguoiPhongVan;
       this.nhanXet = nhanXet;
       this.datYeuCau = datYeuCau;
       this.tinhTrangPhongVan = tinhTrangPhongVan;
       this.ghiChu = ghiChu;
       this.keHoachSo = keHoachSo;
       this.machitietvpv = machitietvpv;
    }
   
    public Integer getIdKqpv() {
        return this.idKqpv;
    }
    
    public void setIdKqpv(Integer idKqpv) {
        this.idKqpv = idKqpv;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public String getNguoiPhongVan() {
        return this.nguoiPhongVan;
    }
    
    public void setNguoiPhongVan(String nguoiPhongVan) {
        this.nguoiPhongVan = nguoiPhongVan;
    }
    public String getNhanXet() {
        return this.nhanXet;
    }
    
    public void setNhanXet(String nhanXet) {
        this.nhanXet = nhanXet;
    }
    public boolean isDatYeuCau() {
        return this.datYeuCau;
    }
    
    public void setDatYeuCau(boolean datYeuCau) {
        this.datYeuCau = datYeuCau;
    }
    public boolean isTinhTrangPhongVan() {
        return this.tinhTrangPhongVan;
    }
    
    public void setTinhTrangPhongVan(boolean tinhTrangPhongVan) {
        this.tinhTrangPhongVan = tinhTrangPhongVan;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
    public String getKeHoachSo() {
        return this.keHoachSo;
    }
    
    public void setKeHoachSo(String keHoachSo) {
        this.keHoachSo = keHoachSo;
    }
    public String getMachitietvpv() {
        return this.machitietvpv;
    }
    
    public void setMachitietvpv(String machitietvpv) {
        this.machitietvpv = machitietvpv;
    }




}


