package model.pojos;
// Generated May 31, 2016 12:16:37 AM by Hibernate Tools 4.3.1



/**
 * Tlu30chitietdktdvpv generated by hbm2java
 */
public class Tlu30chitietdktdvpv  implements java.io.Serializable {


     private Integer id;
     private String tenctdktd;
     private String machitietvpv;
     private float diemphongvan;

    public Tlu30chitietdktdvpv() {
    }

    public Tlu30chitietdktdvpv(String tenctdktd, String machitietvpv, float diemphongvan) {
       this.tenctdktd = tenctdktd;
       this.machitietvpv = machitietvpv;
       this.diemphongvan = diemphongvan;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTenctdktd() {
        return this.tenctdktd;
    }
    
    public void setTenctdktd(String tenctdktd) {
        this.tenctdktd = tenctdktd;
    }
    public String getMachitietvpv() {
        return this.machitietvpv;
    }
    
    public void setMachitietvpv(String machitietvpv) {
        this.machitietvpv = machitietvpv;
    }
    public float getDiemphongvan() {
        return this.diemphongvan;
    }
    
    public void setDiemphongvan(float diemphongvan) {
        this.diemphongvan = diemphongvan;
    }




}


