/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import dunglt.qlns.client.constant.Constant;
import dunglt.qlns.client.util.ClientUtil;
import dunglt.qlns.client.util.ValidateUtil;
import javax.swing.*;
import service.webservice.Tlu20DangNhap;

/**
 *
 * @author dunglt
 */
public class AccountMgt extends javax.swing.JFrame {
    public static String uName;
    public static boolean stUpdate = false;
    /**
     * Creates new form AccountMgt
     */
    public AccountMgt() {
        initComponents();
        this.setResizable(false);
    }
    
    public AccountMgt(boolean isUpdateUser, String Uname) {
        initComponents();
        this.setResizable(false);
        stUpdate = isUpdateUser;
        uName = Uname;
        Tlu20DangNhap dangNhap = tLu20DangNhapFindUser(uName);
        _tfUserName.setText(Uname);
        _tfUserName.disable();
        _cbRole.setSelectedItem(dangNhap.getRole());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        _tfUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        _pfRePass = new javax.swing.JPasswordField();
        _pfPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        _cbRole = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(224, 230, 237));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel1.setText("Tên đăng nhập");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel2.setText("Mật khẩu");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel3.setText("Nhập lại mật khẩu");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel4.setText("Quyền");

        _cbRole.setBackground(java.awt.Color.white);
        _cbRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "admin", "user" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(_tfUserName)
                    .addComponent(_pfRePass)
                    .addComponent(_pfPass)
                    .addComponent(_cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_tfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_pfRePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(67, 66, 213));
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Hủy bỏ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(67, 66, 213));
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Đồng ý");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(stUpdate) {
            if(ValidateUtil.isNotNull(_pfPass.getText()) || ValidateUtil.isNotNull(_pfRePass.getText())) {
                if(!_pfRePass.getText().equals(_pfPass.getText())) {
                    JOptionPane.showMessageDialog(rootPane, "Nhập lại mật khẩu và mật khẩu phải trùng nhau", "warning", JOptionPane.ERROR_MESSAGE);
                }

                else {
                    
                    String mess = Constant.BLANK;
                    mess = tlu20DangNhapUpdate(uName, _pfPass.getText() , _pfRePass.getText(), ClientUtil.setValueofCombobox(_cbRole));
                    if(mess.equals(Constant.SUCCESS)) {
                        JOptionPane.showConfirmDialog(rootPane, "cập nhật thành công");
                    }
                }
            } else {
                String mess = Constant.BLANK;
                Tlu20DangNhap dangNhap = tLu20DangNhapFindUser(uName);
                mess = tlu20DangNhapUpdate(uName, dangNhap.getPasswords() , dangNhap.getPasswords(), ClientUtil.setValueofCombobox(_cbRole));
                    if(mess.equals(Constant.SUCCESS)) {
                        JOptionPane.showConfirmDialog(rootPane, "cập nhật thành công");
                    }
            }
        } else {
            if(!_tfUserName.getText().equals(Constant.BLANK)) {
                Tlu20DangNhap dangNhap = tLu20DangNhapFindUser(_tfUserName.getText());
                if(ValidateUtil.isNull(dangNhap)) {
                    if(ValidateUtil.isNotNull(_pfPass.getText())) {
                        if(_pfRePass.getText().equals(_pfPass.getText())) {
                            String result = Constant.BLANK;
                            result = tlu20DangNhapInsert(_tfUserName.getText(), _pfPass.getText(), _pfRePass.getText(), ClientUtil.setValueofCombobox(_cbRole));
                            if(result.equalsIgnoreCase(Constant.BLANK)) {
                                JOptionPane.showConfirmDialog(rootPane, "thêm thành công");
                            }
                        } 
                        else {
                            JOptionPane.showMessageDialog(rootPane, "Nhập lại mật khẩu và mật khẩu phải trùng nhau", "warning", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Mật khẩu không được để trống", "warning", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Tên đăng nhập không đã tồn tại", "warning", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                
                JOptionPane.showMessageDialog(rootPane, "Tên đăng nhập không được để trống", "warning", JOptionPane.ERROR_MESSAGE);
            }
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox _cbRole;
    private javax.swing.JPasswordField _pfPass;
    private javax.swing.JPasswordField _pfRePass;
    private javax.swing.JTextField _tfUserName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static Tlu20DangNhap tLu20DangNhapFindUser(java.lang.String user) {
        service.webservice.WsDangNhap_Service service = new service.webservice.WsDangNhap_Service();
        service.webservice.WsDangNhap port = service.getWsDangNhapPort();
        return port.tLu20DangNhapFindUser(user);
    }

    private static String tlu20DangNhapInsert(java.lang.String username, java.lang.String pass, java.lang.String repass, java.lang.String role) {
        service.webservice.WsDangNhap_Service service = new service.webservice.WsDangNhap_Service();
        service.webservice.WsDangNhap port = service.getWsDangNhapPort();
        return port.tlu20DangNhapInsert(username, pass, repass, role);
    }

    private static String tlu20DangNhapUpdate(java.lang.String username, java.lang.String pass, java.lang.String repass, java.lang.String role) {
        service.webservice.WsDangNhap_Service service = new service.webservice.WsDangNhap_Service();
        service.webservice.WsDangNhap port = service.getWsDangNhapPort();
        return port.tlu20DangNhapUpdate(username, pass, repass, role);
    }
    
}
