/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import dunglt.qlns.client.util.ClientUtil;
import dunglt.qlns.client.util.DateTimeUtil;
import dunglt.qlns.client.util.DictItem;
import dunglt.qlns.client.util.ValidateUtil;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import service.webservice.ParseException_Exception;
import service.webservice.Tlu30LichPhongVan;

/**
 *
 * @author dunglt
 */
public class updateLPV extends javax.swing.JFrame {
    public static int stIdLpv = 0;
    /**
     * Creates new form updateLPV
     */
    public updateLPV() {
        this.setResizable(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        DictItem.setTenAndMaHs(_cbbUngVienhsuv);
        DictItem.setKhs(_cbbKeHoachTuyenDungLPV);
    }
    
    public updateLPV(boolean isUpdateLpv, int idLpv) {
        stIdLpv = idLpv;
        this.setResizable(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        DictItem.setTenAndMaHs(_cbbUngVienhsuv);
        DictItem.setKhs(_cbbKeHoachTuyenDungLPV);
        
        if(idLpv > 0) {
            Tlu30LichPhongVan lpv = tlu30LpvFindById(idLpv);
            if(ValidateUtil.isNotNull(lpv)) {
                _cbDangLaNhanVienCongTyLPV
                        .setSelectedItem(ClientUtil.getStringFromIsActive(lpv.isIsActive()));
                ClientUtil.checkIsPass(_cbDatYeuCauLPV, lpv.isDatYeuCau());
                _cbbKeHoachTuyenDungLPV.setSelectedItem(lpv.getKeHoachSo());
                _cbbUngVienhsuv.setSelectedItem(lpv.getUngVien());
                _clLichhen.setCalendar(lpv.getLichHen().toGregorianCalendar());
                _clNgayThem.setCalendar(lpv.getCreatedAt().toGregorianCalendar());
                _textariaNhanXetLPV.setText(lpv.getNhanXet());
                _tfNguoiNhapLPV.setText(lpv.getCreatedBy());
                _tfNguoiPhuTrachPhongVanLPV.setText(lpv.getPhuTrachPhongVan());
                _tfPhongVanSoLPV.setText(ClientUtil.convertIntoString(lpv.getSoLichPhongVan()));
                _tfTinhTrangPhongVan.setText(lpv.getTinhTrangPhongVan());
            }
        }
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel() {
            ImageIcon icon = new ImageIcon("/home/dunglt/NetBeansProjects/client/trong.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel42 = new javax.swing.JLabel();
        _tfNguoiNhapLPV = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        _clNgayThem = new com.toedter.calendar.JDateChooser();
        jLabel44 = new javax.swing.JLabel();
        _cbDangLaNhanVienCongTyLPV = new javax.swing.JComboBox();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        _tfPhongVanSoLPV = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        _tfNguoiPhuTrachPhongVanLPV = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        _tfTinhTrangPhongVan = new javax.swing.JTextField();
        lpvChiTiet = new javax.swing.JButton();
        _cbDatYeuCauLPV = new javax.swing.JCheckBox();
        jLabel50 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        _textariaNhanXetLPV = new javax.swing.JTextArea();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        _clLichhen = new com.toedter.calendar.JDateChooser();
        _cbbUngVienhsuv = new javax.swing.JComboBox();
        _cbbKeHoachTuyenDungLPV = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel14.setBackground(java.awt.Color.white);

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel42.setText("Người thêm");

        _tfNguoiNhapLPV.setBackground(java.awt.Color.white);

        jLabel43.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel43.setText("Ngày thêm");

        _clNgayThem.setBackground(java.awt.Color.white);
        _clNgayThem.setDateFormatString("dd-MM-yyyy");

        jLabel44.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel44.setText("Đang là nhân viên công ty");

        _cbDangLaNhanVienCongTyLPV.setBackground(java.awt.Color.white);
        _cbDangLaNhanVienCongTyLPV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Có", "Không" }));

        jLabel45.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel45.setText("Ứng viên");

        jLabel46.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel46.setText("Kế hoạch số");

        jLabel47.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel47.setText("Số lịch phỏng vấn");

        jLabel48.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel48.setText("Người phụ trách phỏng vấn");

        jLabel49.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel49.setText("Tình trạng phỏng vấn");

        lpvChiTiet.setBackground(new java.awt.Color(239, 25, 9));
        lpvChiTiet.setForeground(java.awt.Color.white);
        lpvChiTiet.setText("Chi tiết");
        lpvChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lpvChiTietActionPerformed(evt);
            }
        });

        _cbDatYeuCauLPV.setBackground(java.awt.Color.white);
        _cbDatYeuCauLPV.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        _cbDatYeuCauLPV.setText("Đạt");

        jLabel50.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel50.setText("Nhận xét");

        _textariaNhanXetLPV.setColumns(20);
        _textariaNhanXetLPV.setRows(5);
        jScrollPane7.setViewportView(_textariaNhanXetLPV);

        jButton30.setBackground(new java.awt.Color(52, 79, 223));
        jButton30.setForeground(new java.awt.Color(254, 254, 254));
        jButton30.setText("Đồng ý");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jButton31.setBackground(new java.awt.Color(52, 79, 223));
        jButton31.setForeground(new java.awt.Color(254, 254, 254));
        jButton31.setText("Hủy bỏ");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel51.setText("Lịch hẹn");

        _clLichhen.setBackground(java.awt.Color.white);
        _clLichhen.setDateFormatString("dd-MM-yyyy");

        _cbbUngVienhsuv.setBackground(java.awt.Color.white);

        _cbbKeHoachTuyenDungLPV.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGap(484, 484, 484)
                        .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(585, 585, 585))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jScrollPane7)
                        .addGap(153, 153, 153))))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(593, 593, 593))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(_tfTinhTrangPhongVan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(199, 199, 199))
                            .addComponent(_tfNguoiNhapLPV, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(220, 220, 220))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(195, 195, 195))
                            .addComponent(_cbbUngVienhsuv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_cbbKeHoachTuyenDungLPV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(217, 217, 217))
                            .addComponent(_tfPhongVanSoLPV)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel14Layout.createSequentialGroup()
                                        .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(127, 127, 127))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                        .addComponent(_clNgayThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(43, 43, 43)))
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(_cbDangLaNhanVienCongTyLPV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(208, 208, 208))
                            .addComponent(_tfNguoiPhuTrachPhongVanLPV, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(325, 325, 325))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel14Layout.createSequentialGroup()
                                .addComponent(_clLichhen, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(_cbDatYeuCauLPV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(35, 35, 35)
                                .addComponent(lpvChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(278, 278, 278))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(506, 506, 506)
                .addComponent(jButton30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53)
                .addComponent(jButton31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(495, 495, 495))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_tfNguoiNhapLPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_clNgayThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addComponent(jLabel47)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_cbDangLaNhanVienCongTyLPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_tfPhongVanSoLPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_cbbUngVienhsuv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(jLabel48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_tfNguoiPhuTrachPhongVanLPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_cbbKeHoachTuyenDungLPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(jLabel51))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(_tfTinhTrangPhongVan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(_clLichhen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(_cbDatYeuCauLPV)
                        .addComponent(lpvChiTiet)))
                .addGap(30, 30, 30)
                .addComponent(jLabel50)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton31))
                .addGap(169, 169, 169))
        );

        jPanel14Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton30, jButton31});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(0, 0, 1290, 860);
    }// </editor-fold>//GEN-END:initComponents

    private void lpvChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lpvChiTietActionPerformed
        new ChiTietLpv().setVisible(true);
    }//GEN-LAST:event_lpvChiTietActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        if (ValidateUtil.isNotNull(_tfNguoiNhapLPV.getText())
                && ValidateUtil.isNotNull(_tfPhongVanSoLPV.getText())
                && ValidateUtil.isNotNull(_tfNguoiPhuTrachPhongVanLPV.getText())
                && ValidateUtil.isNotNull(_tfNguoiPhuTrachPhongVanLPV.getText())) {
                int solichphongvan = Integer.parseInt(_tfPhongVanSoLPV.getText());
                if(stIdLpv == 0) {
                    if (tlu30LpvFindbySoLPV(solichphongvan).isEmpty()) {
                    try {
                        tlu30LpvInsert(_tfNguoiNhapLPV.getText(), 
                                DateTimeUtil.convertCalendarToString(_clNgayThem.getCalendar().getTime()),
                                ClientUtil.getBooleanFromIsActiveCbb(
                                        ClientUtil.setValueofCombobox(_cbDangLaNhanVienCongTyLPV)), 
                                ClientUtil.setValueofCombobox(_cbbUngVienhsuv),
                                ClientUtil.setValueofCombobox(_cbbKeHoachTuyenDungLPV), 
                                solichphongvan, 
                                DateTimeUtil.convertCalendarToString(_clLichhen.getCalendar().getTime()),
                                _tfNguoiPhuTrachPhongVanLPV.getText(), 
                                _tfTinhTrangPhongVan.getText(), 
                                ClientUtil.isactiveCheckBox(_cbDatYeuCauLPV), 
                                _textariaNhanXetLPV.getText());
                        JOptionPane.showMessageDialog(rootPane, "Thêm mới thành công");
                    } catch (Exception e) {}
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Đã tồn tại số lịch phỏng vấn");
                }
             } else {
                    try { 
                        tlu30LpvUpdate(stIdLpv, _tfNguoiNhapLPV.getText(),
                                DateTimeUtil.convertCalendarToString(_clNgayThem.getCalendar().getTime()),
                                ClientUtil.getBooleanFromIsActiveCbb(
                                        ClientUtil.setValueofCombobox(_cbDangLaNhanVienCongTyLPV)), 
                                ClientUtil.setValueofCombobox(_cbbUngVienhsuv),
                                ClientUtil.setValueofCombobox(_cbbKeHoachTuyenDungLPV),
                                solichphongvan, 
                                DateTimeUtil.convertCalendarToString(_clLichhen.getCalendar().getTime()),
                                _tfNguoiPhuTrachPhongVanLPV.getText(),
                                _tfTinhTrangPhongVan.getText(),
                                ClientUtil.isactiveCheckBox(_cbDatYeuCauLPV), 
                                _textariaNhanXetLPV.getText());
                    } catch (ParseException_Exception ex) {
                        Logger.getLogger(updateLPV.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

        } else {
            JOptionPane.showMessageDialog(rootPane, "chưa điền đủ thông tin");
        }
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton31ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateLPV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateLPV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateLPV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateLPV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateLPV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox _cbDangLaNhanVienCongTyLPV;
    private javax.swing.JCheckBox _cbDatYeuCauLPV;
    private javax.swing.JComboBox _cbbKeHoachTuyenDungLPV;
    private javax.swing.JComboBox _cbbUngVienhsuv;
    private com.toedter.calendar.JDateChooser _clLichhen;
    private com.toedter.calendar.JDateChooser _clNgayThem;
    private javax.swing.JTextArea _textariaNhanXetLPV;
    private javax.swing.JTextField _tfNguoiNhapLPV;
    private javax.swing.JTextField _tfNguoiPhuTrachPhongVanLPV;
    private javax.swing.JTextField _tfPhongVanSoLPV;
    private javax.swing.JTextField _tfTinhTrangPhongVan;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton lpvChiTiet;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<service.webservice.Tlu30LichPhongVan> tlu30LpvFindbySoLPV(int soLpv) {
        service.webservice.WsTlu30LichPhongVan_Service service = new service.webservice.WsTlu30LichPhongVan_Service();
        service.webservice.WsTlu30LichPhongVan port = service.getWsTlu30LichPhongVanPort();
        return port.tlu30LpvFindbySoLPV(soLpv);
    }

    private static String tlu30LpvInsert(java.lang.String createdBy, java.lang.String createdAt, boolean isActive, java.lang.String ungVien, java.lang.String keHoachSo, int soLichPhongVan, java.lang.String lichHen, java.lang.String phuTrachPhongVan, java.lang.String tinhTrangPhongVan, boolean datYeuCau, java.lang.String nhanXet) throws ParseException_Exception {
        service.webservice.WsTlu30LichPhongVan_Service service = new service.webservice.WsTlu30LichPhongVan_Service();
        service.webservice.WsTlu30LichPhongVan port = service.getWsTlu30LichPhongVanPort();
        return port.tlu30LpvInsert(createdBy, createdAt, isActive, ungVien, keHoachSo, soLichPhongVan, lichHen, phuTrachPhongVan, tinhTrangPhongVan, datYeuCau, nhanXet);
    }

    private static Tlu30LichPhongVan tlu30LpvFindById(int id) {
        service.webservice.WsTlu30LichPhongVan_Service service = new service.webservice.WsTlu30LichPhongVan_Service();
        service.webservice.WsTlu30LichPhongVan port = service.getWsTlu30LichPhongVanPort();
        return port.tlu30LpvFindById(id);
    }

    private static String tlu30LpvUpdate(int idLpv, java.lang.String createdBy, java.lang.String createdAt, boolean isActive, java.lang.String ungVien, java.lang.String keHoachSo, int soLichPhongVan, java.lang.String lichHen, java.lang.String phuTrachPhongVan, java.lang.String tinhTrangPhongVan, boolean datYeuCau, java.lang.String nhanXet) throws ParseException_Exception {
        service.webservice.WsTlu30LichPhongVan_Service service = new service.webservice.WsTlu30LichPhongVan_Service();
        service.webservice.WsTlu30LichPhongVan port = service.getWsTlu30LichPhongVanPort();
        return port.tlu30LpvUpdate(idLpv, createdBy, createdAt, isActive, ungVien, keHoachSo, soLichPhongVan, lichHen, phuTrachPhongVan, tinhTrangPhongVan, datYeuCau, nhanXet);
    }
}
