/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import dunglt.qlns.client.util.ClientUtil;
import dunglt.qlns.client.util.DateTimeUtil;
import dunglt.qlns.client.util.DictItem;
import dunglt.qlns.client.util.ValidateUtil;
import java.awt.*;
import javax.swing.*;
import service.webservice.ParseException_Exception;
import service.webservice.Tlu30KeHoachTuyenDung;

/**
 *
 * @author dunglt
 */
public class updateKHTD extends javax.swing.JFrame {
    /**
     * declare static local variable
     */
        
        private static int stIdKhtd = 0;
    
    /**
     * end declare static local variable
     */
        
        
    /**
     * Creates new form updateKHTD
     */
    public updateKHTD() {
        this.setResizable(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        DictItem.setKhs(_cbbKHS);
        DictItem.setBoPhan(_cbbKhtdBoPhan);
        DictItem.setChucVu(_cbbChucVudktd);
        DictItem.setTDVH(_cbbKhtdTdvh);
    }
    
     public updateKHTD(int idDktd, boolean isUpdateKhtd) {
        stIdKhtd = idDktd;
        this.setResizable(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        DictItem.setKhs(_cbbKHS);
        DictItem.setBoPhan(_cbbKhtdBoPhan);
        DictItem.setChucVu(_cbbChucVudktd);
        DictItem.setTDVH(_cbbKhtdTdvh);
         if(isUpdateKhtd) {
            Tlu30KeHoachTuyenDung khtd = tlu20KhtdFindById(idDktd);
            if(ValidateUtil.isNotNull(khtd)) {
                _calNgayThem.setCalendar(khtd.getCreatedAt().toGregorianCalendar());
                _calNgayKeHoach.setCalendar(khtd.getNgayKeHoach().toGregorianCalendar());
                _cbbChucVudktd.setSelectedItem(khtd.getChucVu());
                _cbbIsActive.setSelectedItem(ClientUtil.getStringFromIsActive(khtd.isIsActive()));
                _cbbKHS.setSelectedItem(khtd.getKeHoachSo());
                _cbbKhtdBoPhan.setSelectedItem(khtd.getBoPhan());
                _cbbKhtdSex.setSelectedItem(khtd.getGioiTinh());
                _cbbKhtdTdvh.setSelectedItem(khtd.getTrinhDoVanHoa());
                _spSoLuong.setValue(khtd.getSoLuong());
                _spTuoiMax.setValue(khtd.getTuoiMax());
                _spTuoiMin.setValue(khtd.getTuoiMin());
                _taGhiChu.setText(khtd.getGhiChu());
                _tfKhtdCreatedBy.setText(khtd.getCreatedBy());
                _tfKhtdKinhNghiem.setText(khtd.getKinhNghiem());
                _tfKhtdNoiLamViec.setText(khtd.getNoiLamViec());
            } else {
                System.out.println("null");
            }
        }
     }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            ImageIcon icon = new ImageIcon("/home/dunglt/NetBeansProjects/client/trong.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        _tfKhtdCreatedBy = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        _calNgayThem = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        _cbbKHS = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        _cbbKhtdBoPhan = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        _cbbChucVudktd = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        _cbbKhtdTdvh = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        _spSoLuong = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        _spTuoiMin = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        _spTuoiMax = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        _tfKhtdNoiLamViec = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        _cbbIsActive = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        _cbbKhtdSex = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        _tfKhtdKinhNghiem = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        _calNgayKeHoach = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        _taGhiChu = new javax.swing.JTextArea();
        ukhtdDongY = new javax.swing.JButton();
        ukhtdHuyBo = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1150, 741));

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(1150, 741));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel1.setText("Người Thêm");

        _tfKhtdCreatedBy.setBackground(java.awt.Color.white);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel2.setText("Ngày thêm");

        _calNgayThem.setBackground(java.awt.Color.white);
        _calNgayThem.setDateFormatString("dd-MM-yyyy");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel3.setText("Kê hoạch số");

        _cbbKHS.setBackground(java.awt.Color.white);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel4.setText("Bộ phận");

        _cbbKhtdBoPhan.setBackground(java.awt.Color.white);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel5.setText("Chức vụ");

        _cbbChucVudktd.setBackground(java.awt.Color.white);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel6.setText("Trình độ văn hóa");

        _cbbKhtdTdvh.setBackground(java.awt.Color.white);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel7.setText("Số lượng");

        _spSoLuong.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel8.setText("Tuổi từ");

        _spTuoiMin.setModel(new javax.swing.SpinnerNumberModel(18, 18, 65, 1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel9.setText("Đến");

        _spTuoiMax.setModel(new javax.swing.SpinnerNumberModel(18, 18, 65, 1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel10.setText("Nơi làm việc");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel11.setText("Đang là nhân viên công ty");

        _cbbIsActive.setBackground(java.awt.Color.white);
        _cbbIsActive.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Có", "Không" }));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel12.setText("Giới tính");

        _cbbKhtdSex.setBackground(java.awt.Color.white);
        _cbbKhtdSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel13.setText("Kinh nghiệm");

        _tfKhtdKinhNghiem.setBackground(java.awt.Color.white);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel14.setText("Ngày kế hoạch");

        _calNgayKeHoach.setBackground(java.awt.Color.white);
        _calNgayKeHoach.setDateFormatString("dd-MM-yyyy");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel15.setText("Ghi chú");

        _taGhiChu.setBackground(java.awt.Color.white);
        _taGhiChu.setColumns(20);
        _taGhiChu.setRows(5);
        _taGhiChu.setPreferredSize(new java.awt.Dimension(240, 300));
        jScrollPane1.setViewportView(_taGhiChu);

        ukhtdDongY.setBackground(new java.awt.Color(52, 79, 223));
        ukhtdDongY.setForeground(java.awt.Color.white);
        ukhtdDongY.setText("Đồng Ý");
        ukhtdDongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukhtdDongYActionPerformed(evt);
            }
        });

        ukhtdHuyBo.setBackground(new java.awt.Color(52, 79, 223));
        ukhtdHuyBo.setForeground(java.awt.Color.white);
        ukhtdHuyBo.setText("Hủy Bỏ");
        ukhtdHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukhtdHuyBoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel16.setText("Cấu hình");

        jButton1.setBackground(java.awt.Color.red);
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Cấu hình");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addComponent(ukhtdDongY, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(ukhtdHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jScrollPane1)
                .addGap(140, 140, 140))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(_tfKhtdKinhNghiem, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(_tfKhtdNoiLamViec, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(_spSoLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                        .addComponent(_cbbChucVudktd, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_cbbKHS, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(_tfKhtdCreatedBy, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel13))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel15)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_calNgayThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(_spTuoiMin, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_cbbKhtdSex, 0, 143, Short.MAX_VALUE)
                                    .addComponent(_spTuoiMax)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel12))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(_calNgayKeHoach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_cbbKhtdTdvh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_cbbKhtdBoPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(_cbbIsActive, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(262, 262, 262))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_tfKhtdCreatedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_calNgayThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel16))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(_cbbKHS)
                        .addComponent(_cbbKhtdBoPhan))
                    .addComponent(jButton1))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_cbbChucVudktd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_cbbKhtdTdvh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_spSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_spTuoiMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_spTuoiMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_tfKhtdNoiLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_cbbIsActive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_cbbKhtdSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_tfKhtdKinhNghiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_calNgayKeHoach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ukhtdDongY, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ukhtdHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1235, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1245, 583);
    }// </editor-fold>//GEN-END:initComponents

    private void ukhtdDongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukhtdDongYActionPerformed
        int tuoimin, tuoimax;
        tuoimin = ClientUtil.setValueofSpinner(_spTuoiMin);
        tuoimax = ClientUtil.setValueofSpinner(_spTuoiMax);
       
            if (tuoimax > tuoimin) {
                if (ValidateUtil.isNotNull(_tfKhtdCreatedBy.getText())
                        && ValidateUtil.isNotNull(_tfKhtdNoiLamViec) 
                        && ValidateUtil.isNotNull(_tfKhtdKinhNghiem)) {
                    try {

                        if(stIdKhtd == 0) {
                            tlu30KhtdInsert(_tfKhtdCreatedBy.getText(), 
                                DateTimeUtil.convertCalendarToString(_calNgayThem.getCalendar().getTime()),
                                ClientUtil.getBooleanFromIsActiveCbb(ClientUtil.setValueofCombobox(_cbbIsActive)),
                                ClientUtil.setValueofCombobox(_cbbKHS), 
                                DateTimeUtil.convertCalendarToString(_calNgayKeHoach.getCalendar().getTime()),
                                ClientUtil.setValueofCombobox(_cbbKhtdBoPhan), 
                                ClientUtil.setValueofCombobox(_cbbChucVudktd), 
                                ClientUtil.setValueofCombobox(_cbbKhtdTdvh),
                                ClientUtil.setValueofSpinner(_spSoLuong), 
                                ClientUtil.setValueofCombobox(_cbbKhtdSex), tuoimin, tuoimax,
                                _tfKhtdNoiLamViec.getText(), _tfKhtdKinhNghiem.getText(), 
                                _taGhiChu.getText());
                            JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                        } else {
                            tlu30KhtdUpdateById(stIdKhtd,_tfKhtdCreatedBy.getText(), 
                                DateTimeUtil.convertCalendarToString(_calNgayThem.getCalendar().getTime()),
                                ClientUtil.getBooleanFromIsActiveCbb(ClientUtil.setValueofCombobox(_cbbIsActive)),
                                ClientUtil.setValueofCombobox(_cbbKHS), 
                                DateTimeUtil.convertCalendarToString(_calNgayKeHoach.getCalendar().getTime()),
                                ClientUtil.setValueofCombobox(_cbbKhtdBoPhan), 
                                ClientUtil.setValueofCombobox(_cbbChucVudktd), 
                                ClientUtil.setValueofCombobox(_cbbKhtdTdvh),
                                ClientUtil.setValueofSpinner(_spSoLuong), 
                                ClientUtil.setValueofCombobox(_cbbKhtdSex), tuoimin, tuoimax,
                                _tfKhtdNoiLamViec.getText(), _tfKhtdKinhNghiem.getText(), 
                                _taGhiChu.getText());
                            JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công");
                        }

                    } catch (Exception ex) {
                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Các trường màu đỏ không được bỏ trống");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Tuổi TỪ phải nhỏ hơn tuổi ĐẾN");
            }
    }//GEN-LAST:event_ukhtdDongYActionPerformed

    private void ukhtdHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukhtdHuyBoActionPerformed
       dispose();
    }//GEN-LAST:event_ukhtdHuyBoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new TieuChiKHTD().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser _calNgayKeHoach;
    private com.toedter.calendar.JDateChooser _calNgayThem;
    private javax.swing.JComboBox _cbbChucVudktd;
    private javax.swing.JComboBox _cbbIsActive;
    private javax.swing.JComboBox _cbbKHS;
    private javax.swing.JComboBox _cbbKhtdBoPhan;
    private javax.swing.JComboBox _cbbKhtdSex;
    private javax.swing.JComboBox _cbbKhtdTdvh;
    private javax.swing.JSpinner _spSoLuong;
    private javax.swing.JSpinner _spTuoiMax;
    private javax.swing.JSpinner _spTuoiMin;
    private javax.swing.JTextArea _taGhiChu;
    private javax.swing.JTextField _tfKhtdCreatedBy;
    private javax.swing.JTextField _tfKhtdKinhNghiem;
    private javax.swing.JTextField _tfKhtdNoiLamViec;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ukhtdDongY;
    private javax.swing.JButton ukhtdHuyBo;
    // End of variables declaration//GEN-END:variables

    private static String tlu30KhtdInsert(java.lang.String createdby, java.lang.String createdat, boolean isactive, java.lang.String kehoachso, java.lang.String ngaykehoach, java.lang.String bophan, java.lang.String chucvu, java.lang.String trinhdovanhoa, int soluong, java.lang.String gioitinh, int tuoimin, int tuoimax, java.lang.String noilamviec, java.lang.String kinhnghiem, java.lang.String ghichu) throws ParseException_Exception {
        service.webservice.WsTLU30KeHoachTuyenDung service = new service.webservice.WsTLU30KeHoachTuyenDung();
        service.webservice.WsTlu30KeHoachTuyenDung port = service.getWsTlu30KeHoachTuyenDungPort();
        return port.tlu30KhtdInsert(createdby, createdat, isactive, kehoachso, ngaykehoach, bophan, chucvu, trinhdovanhoa, soluong, gioitinh, tuoimin, tuoimax, noilamviec, kinhnghiem, ghichu);
    }

    private static Tlu30KeHoachTuyenDung tlu20KhtdFindById(int id) {
        service.webservice.WsTLU30KeHoachTuyenDung service = new service.webservice.WsTLU30KeHoachTuyenDung();
        service.webservice.WsTlu30KeHoachTuyenDung port = service.getWsTlu30KeHoachTuyenDungPort();
        return port.tlu20KhtdFindById(id);
    }

    private static String tlu30KhtdUpdateById(int idkhtd, java.lang.String createdby, java.lang.String createdat, boolean isactive, java.lang.String kehoachso, java.lang.String ngaykehoach, java.lang.String bophan, java.lang.String chucvu, java.lang.String trinhdovanhoa, int soluong, java.lang.String gioitinh, int tuoimin, int tuoimax, java.lang.String noilamviec, java.lang.String kinhnghiem, java.lang.String ghichu) throws ParseException_Exception {
        service.webservice.WsTLU30KeHoachTuyenDung service = new service.webservice.WsTLU30KeHoachTuyenDung();
        service.webservice.WsTlu30KeHoachTuyenDung port = service.getWsTlu30KeHoachTuyenDungPort();
        return port.tlu30KhtdUpdateById(idkhtd, createdby, createdat, isactive, kehoachso, ngaykehoach, bophan, chucvu, trinhdovanhoa, soluong, gioitinh, tuoimin, tuoimax, noilamviec, kinhnghiem, ghichu);
    }
}
