/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import dunglt.qlns.client.constant.Constant;
import dunglt.qlns.client.util.ClientUtil;
import dunglt.qlns.client.util.DateTimeUtil;
import dunglt.qlns.client.util.DictItem;
import dunglt.qlns.client.util.ValidateUtil;
import java.awt.*;
import javax.swing.*;
import service.webservice.ParseException_Exception;
import service.webservice.Tlu30HoSoUngVien;

/**
 *
 * @author dunglt
 */
public class updateHSUV extends javax.swing.JFrame {
    /**
     * start declare constant local variable
     */
    
        private static int stidHsuv = 0;
    
    /**
     * start declare constant local variable
     */
    
    
    /**
     * Creates new form updateHSUV
     */
    public updateHSUV() {
        this.setResizable(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
       DictItem.setKhs(_cbbKeHoachSoHSUV);
        DictItem.setBoPhan(_cbbBoPhanDuTuyenHSUV);
        DictItem.setTDVH(_cbbTrinhDoVanHoaHSUV);
    }
    
    public updateHSUV(boolean isUpdateHsuv, int idHsuv) {
        stidHsuv = idHsuv;
        this.setResizable(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        DictItem.setKhs(_cbbKeHoachSoHSUV);
        DictItem.setBoPhan(_cbbBoPhanDuTuyenHSUV);
        DictItem.setTDVH(_cbbTrinhDoVanHoaHSUV);
        if(isUpdateHsuv) {
            Tlu30HoSoUngVien hsuv = findById(idHsuv);
            if(ValidateUtil.isNotNull(hsuv)) {
                ClientUtil.checkSelected(_cbCMNDHSUV , hsuv.getKemCmdn());
                ClientUtil.checkSelected(_cbDonXinViecHSUV , hsuv.getKemDonXinViec());
                ClientUtil.checkSelected(_cbGiayKhamSucKhoeHSUV , hsuv.getKemGiayKhamSucKhoe());
                ClientUtil.checkSelected(_cbHoKhauHSUV , hsuv.getKemHoKhau());
                ClientUtil.checkSelected(_cbSoYeuLyLichHSUV , hsuv.getKemSoYeuLyLich());
                _cbbBoPhanDuTuyenHSUV.setSelectedItem(hsuv.getBoPhanDuTuyen());
                _cbbGioiTinhHSUV.setSelectedItem(hsuv.getGioiTinh());
                _cbbIstactive.setSelectedItem(ClientUtil.getStringFromIsActive(hsuv.isIsActive()));
                _cbbKeHoachSoHSUV.setSelectedItem(hsuv.getKeHoachSo());
                _cbbTrinhDoVanHoaHSUV.setSelectedItem(hsuv.getTrinhDoVanHoa());
                _clNgayNhan.setCalendar(hsuv.getNgayNhanHoSo().toGregorianCalendar());
                _clNgayNhap.setCalendar(hsuv.getNgayNhanHoSo().toGregorianCalendar());
                _jtextareaBangCapHSUV.setText(hsuv.getGiayToKhac());
                _tfCMNDHSUV.setText(ClientUtil.convertIntoString(hsuv.getCmdn()));
                _tfEmailHSUV.setText(hsuv.getEmail());
                _tfGhiChuHSUV.setText(hsuv.getGhiChu());
                _tfHoTenHSUV.setText(hsuv.getHoTen());
                _tfKinhNghiemHSUV.setText(hsuv.getKinhNghiem());
                _tfMaHosoHSUV.setText(hsuv.getMaHoSo());
                _tfNguoiNhapHSUV.setText(hsuv.getCreatedBy());
                _tfSoDienThoaiHSUV.setText(
                    ClientUtil.convertIntoString(hsuv.getDienThoai()));
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel() {
            ImageIcon icon = new ImageIcon("/home/dunglt/NetBeansProjects/client/trong.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel16 = new javax.swing.JLabel();
        _tfNguoiNhapHSUV = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        _clNgayNhap = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        _tfMaHosoHSUV = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        _clNgayNhan = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        _cbbKeHoachSoHSUV = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        _cbbBoPhanDuTuyenHSUV = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        _cbbTrinhDoVanHoaHSUV = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        _tfHoTenHSUV = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        _cbbGioiTinhHSUV = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        _tfSoDienThoaiHSUV = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        _tfEmailHSUV = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        _tfCMNDHSUV = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        _cbDonXinViecHSUV = new javax.swing.JCheckBox();
        _cbGiayKhamSucKhoeHSUV = new javax.swing.JCheckBox();
        _cbHoKhauHSUV = new javax.swing.JCheckBox();
        _cbCMNDHSUV = new javax.swing.JCheckBox();
        _cbSoYeuLyLichHSUV = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        _jtextareaBangCapHSUV = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        _tfKinhNghiemHSUV = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        _tfGhiChuHSUV = new javax.swing.JTextArea();
        uhsuvDongY = new javax.swing.JButton();
        uhsuvHuyBo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        _cbbIstactive = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1150, 741));

        jPanel3.setPreferredSize(new java.awt.Dimension(1150, 741));
        jPanel3.setRequestFocusEnabled(false);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel16.setText("Người nhập");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel17.setText("Ngày nhập");

        _clNgayNhap.setDateFormatString("dd-MM-yyyy");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel18.setText("Số hồ sơ");

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel19.setText("Ngày nhận hồ sơ");

        _clNgayNhan.setDateFormatString("dd-MM-yyyy");

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel20.setText("Kế hoạch số");

        _cbbKeHoachSoHSUV.setBackground(java.awt.Color.white);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel21.setText("Bộ phận");

        _cbbBoPhanDuTuyenHSUV.setBackground(java.awt.Color.white);
        _cbbBoPhanDuTuyenHSUV.setForeground(java.awt.Color.white);

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel22.setText("Trình độ văn hóa");

        _cbbTrinhDoVanHoaHSUV.setBackground(java.awt.Color.white);

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel23.setText("Họ tên");

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel24.setText("Giới tính");

        _cbbGioiTinhHSUV.setBackground(java.awt.Color.white);
        _cbbGioiTinhHSUV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel25.setText("Số điện thoại");

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel26.setText("Địa chỉ email");

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel27.setText("Số chứng minh nhân dân");

        jScrollPane3.setBackground(java.awt.Color.white);

        jPanel4.setBackground(java.awt.Color.white);

        _cbDonXinViecHSUV.setText("Đơn Xin Việc");

        _cbGiayKhamSucKhoeHSUV.setText("Giấy Khám Sức Khỏe");

        _cbHoKhauHSUV.setText("Hộ Khẩu");

        _cbCMNDHSUV.setText("CMND");
        _cbCMNDHSUV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _cbCMNDHSUVActionPerformed(evt);
            }
        });

        _cbSoYeuLyLichHSUV.setText("Sơ Yếu Lý Lịch");
        _cbSoYeuLyLichHSUV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _cbSoYeuLyLichHSUVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_cbHoKhauHSUV)
                    .addComponent(_cbSoYeuLyLichHSUV, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_cbDonXinViecHSUV, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_cbCMNDHSUV)
                    .addComponent(_cbGiayKhamSucKhoeHSUV, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(_cbSoYeuLyLichHSUV, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_cbDonXinViecHSUV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_cbGiayKhamSucKhoeHSUV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_cbCMNDHSUV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_cbHoKhauHSUV)
                .addContainerGap())
        );

        jScrollPane3.setViewportView(jPanel4);

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel28.setText("Giầy tờ đính kèm");

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel29.setText("Bằng cấp và giấy tờ khác");

        _jtextareaBangCapHSUV.setColumns(20);
        _jtextareaBangCapHSUV.setRows(5);
        jScrollPane4.setViewportView(_jtextareaBangCapHSUV);

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel30.setText("Kinh nghiệm");

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel31.setText("Ghi chú");

        _tfGhiChuHSUV.setColumns(20);
        _tfGhiChuHSUV.setRows(5);
        jScrollPane5.setViewportView(_tfGhiChuHSUV);

        uhsuvDongY.setBackground(new java.awt.Color(52, 79, 223));
        uhsuvDongY.setForeground(java.awt.Color.white);
        uhsuvDongY.setText("Đồng Ý");
        uhsuvDongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uhsuvDongYActionPerformed(evt);
            }
        });

        uhsuvHuyBo.setBackground(new java.awt.Color(52, 79, 223));
        uhsuvHuyBo.setForeground(java.awt.Color.white);
        uhsuvHuyBo.setText("Hủy Bỏ");
        uhsuvHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uhsuvHuyBoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel1.setText("Đang là nhân viên công ty");

        _cbbIstactive.setBackground(java.awt.Color.white);
        _cbbIstactive.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Có", "Không" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(105, 105, 105))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(138, 138, 138))
                    .addComponent(_cbbTrinhDoVanHoaHSUV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_cbbKeHoachSoHSUV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_tfMaHosoHSUV)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(140, 140, 140))
                    .addComponent(_tfNguoiNhapHSUV)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(159, 159, 159))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(135, 135, 135))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(108, 108, 108))
                    .addComponent(_tfKinhNghiemHSUV)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(77, 77, 77)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(202, 202, 202))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(285, 285, 285))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(312, 312, 312))
                    .addComponent(_cbbBoPhanDuTuyenHSUV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(323, 323, 323))
                    .addComponent(_tfHoTenHSUV)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(11, 11, 11))
                            .addComponent(_cbbGioiTinhHSUV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(147, 147, 147))
                            .addComponent(_tfSoDienThoaiHSUV)))
                    .addComponent(_tfEmailHSUV)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(309, 309, 309))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(39, 39, 39))
                                        .addComponent(_clNgayNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(42, 42, 42))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(99, 99, 99)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(_clNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(15, 15, 15))
                            .addComponent(_tfCMNDHSUV)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_cbbIstactive, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(252, 252, 252))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(447, 447, 447)
                .addComponent(uhsuvDongY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(61, 61, 61)
                .addComponent(uhsuvHuyBo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(430, 430, 430))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(_tfNguoiNhapHSUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_clNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_cbbIstactive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_tfMaHosoHSUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_clNgayNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_tfCMNDHSUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_cbbKeHoachSoHSUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_cbbBoPhanDuTuyenHSUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_cbbTrinhDoVanHoaHSUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_tfHoTenHSUV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_cbbGioiTinhHSUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_tfSoDienThoaiHSUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_tfKinhNghiemHSUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(_tfEmailHSUV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uhsuvDongY, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uhsuvHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(229, 229, 229))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1198, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(0, 0, 1160, 771);
    }// </editor-fold>//GEN-END:initComponents

    private void _cbCMNDHSUVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__cbCMNDHSUVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__cbCMNDHSUVActionPerformed

    private void _cbSoYeuLyLichHSUVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__cbSoYeuLyLichHSUVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__cbSoYeuLyLichHSUVActionPerformed

    private void uhsuvDongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uhsuvDongYActionPerformed
        if (stidHsuv == 0) {

                if (ValidateUtil.isNotNull(_tfNguoiNhapHSUV.getText()) 
                        && ValidateUtil.isNotNull(_tfMaHosoHSUV.getText())
                        && ValidateUtil.isNotNull(_tfKinhNghiemHSUV.getText())
                        && ValidateUtil.isNotNull(_tfHoTenHSUV.getText())
                        && ValidateUtil.isNotNull(_tfSoDienThoaiHSUV.getText()) 
                        && ValidateUtil.isNotNull(_tfEmailHSUV.getText())) {
                    try {
                        if(stidHsuv == 0) {
                            tlu30HsuvInsert(
                                _tfNguoiNhapHSUV.getText(), 
                                DateTimeUtil.convertCalendarToString(_clNgayNhap.getCalendar().getTime()),
                                ClientUtil.getBooleanFromIsActiveCbb(ClientUtil.setValueofCombobox(_cbbIstactive)), 
                                _tfMaHosoHSUV.getText(), 
                                DateTimeUtil.convertCalendarToString(_clNgayNhan.getCalendar().getTime()),
                                ClientUtil.setValueofCombobox(_cbbKeHoachSoHSUV), 
                                ClientUtil.setValueofCombobox(_cbbBoPhanDuTuyenHSUV),
                                ClientUtil.setValueofCombobox(_cbbTrinhDoVanHoaHSUV),
                                _tfHoTenHSUV.getText(),
                                ClientUtil.setValueofCombobox(_cbbGioiTinhHSUV),
                                Integer.parseInt(_tfCMNDHSUV.getText()),
                                Integer.parseInt(_tfSoDienThoaiHSUV.getText()),
                                _tfEmailHSUV.getText(), _tfKinhNghiemHSUV.getText(),
                                _tfGhiChuHSUV.getText(),
                                ClientUtil.setvalueofCheckbox(_cbSoYeuLyLichHSUV),
                                ClientUtil.setvalueofCheckbox(_cbDonXinViecHSUV), 
                                ClientUtil.setvalueofCheckbox(_cbGiayKhamSucKhoeHSUV),
                                ClientUtil.setvalueofCheckbox(_cbCMNDHSUV),
                                ClientUtil.setvalueofCheckbox(_cbHoKhauHSUV), 
                                _jtextareaBangCapHSUV.getText(), Constant.BLANK
                            );
                            JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                        } else {
                            tlu30HsuvUpdate(stidHsuv,_tfNguoiNhapHSUV.getText(), 
                                DateTimeUtil.convertCalendarToString(_clNgayNhap.getCalendar().getTime()),
                                ClientUtil.getBooleanFromIsActiveCbb(ClientUtil.setValueofCombobox(_cbbIstactive)), 
                                _tfMaHosoHSUV.getText(), 
                                DateTimeUtil.convertCalendarToString(_clNgayNhan.getCalendar().getTime()),
                                ClientUtil.setValueofCombobox(_cbbKeHoachSoHSUV), 
                                ClientUtil.setValueofCombobox(_cbbBoPhanDuTuyenHSUV),
                                ClientUtil.setValueofCombobox(_cbbTrinhDoVanHoaHSUV),
                                _tfHoTenHSUV.getText(),
                                ClientUtil.setValueofCombobox(_cbbGioiTinhHSUV),
                                Integer.parseInt(_tfCMNDHSUV.getText()),
                                Integer.parseInt(_tfSoDienThoaiHSUV.getText()),
                                _tfEmailHSUV.getText(), _tfKinhNghiemHSUV.getText(),
                                _tfGhiChuHSUV.getText(),
                                ClientUtil.setvalueofCheckbox(_cbSoYeuLyLichHSUV),
                                ClientUtil.setvalueofCheckbox(_cbDonXinViecHSUV), 
                                ClientUtil.setvalueofCheckbox(_cbGiayKhamSucKhoeHSUV),
                                ClientUtil.setvalueofCheckbox(_cbCMNDHSUV),
                                ClientUtil.setvalueofCheckbox(_cbHoKhauHSUV), 
                                _jtextareaBangCapHSUV.getText(), Constant.BLANK);
                            JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công");
                        }
                    } catch (Exception e) {}

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Chưa điền đủ thông tin");
                }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Đã tồn tại mã hồ sơ " + _tfMaHosoHSUV.getText());
        }
    }//GEN-LAST:event_uhsuvDongYActionPerformed

    private void uhsuvHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uhsuvHuyBoActionPerformed
        dispose();
    }//GEN-LAST:event_uhsuvHuyBoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox _cbCMNDHSUV;
    private javax.swing.JCheckBox _cbDonXinViecHSUV;
    private javax.swing.JCheckBox _cbGiayKhamSucKhoeHSUV;
    private javax.swing.JCheckBox _cbHoKhauHSUV;
    private javax.swing.JCheckBox _cbSoYeuLyLichHSUV;
    private javax.swing.JComboBox _cbbBoPhanDuTuyenHSUV;
    private javax.swing.JComboBox _cbbGioiTinhHSUV;
    private javax.swing.JComboBox _cbbIstactive;
    private javax.swing.JComboBox _cbbKeHoachSoHSUV;
    private javax.swing.JComboBox _cbbTrinhDoVanHoaHSUV;
    private com.toedter.calendar.JDateChooser _clNgayNhan;
    private com.toedter.calendar.JDateChooser _clNgayNhap;
    private javax.swing.JTextArea _jtextareaBangCapHSUV;
    private javax.swing.JTextField _tfCMNDHSUV;
    private javax.swing.JTextField _tfEmailHSUV;
    private javax.swing.JTextArea _tfGhiChuHSUV;
    private javax.swing.JTextField _tfHoTenHSUV;
    private javax.swing.JTextField _tfKinhNghiemHSUV;
    private javax.swing.JTextField _tfMaHosoHSUV;
    private javax.swing.JTextField _tfNguoiNhapHSUV;
    private javax.swing.JTextField _tfSoDienThoaiHSUV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton uhsuvDongY;
    private javax.swing.JButton uhsuvHuyBo;
    // End of variables declaration//GEN-END:variables

    private static String tlu30HsuvInsert(java.lang.String createdBy, java.lang.String createdAt, boolean isActive, java.lang.String maHoSo, java.lang.String ngayNhanHoSo, java.lang.String keHoachSo, java.lang.String boPhanDuTuyen, java.lang.String trinhDoVanHoa, java.lang.String hoTen, java.lang.String gioiTinh, int cmdn, int dienThoai, java.lang.String email, java.lang.String kinhNghiem, java.lang.String ghiChu, java.lang.String kemSoYeuLyLich, java.lang.String kemDonXinViec, java.lang.String kemGiayKhamSucKhoe, java.lang.String kemCmd, java.lang.String kemHoKhau, java.lang.String kemBangCap, java.lang.String giayToKhac) throws ParseException_Exception {
        service.webservice.WsTlu30HoSoUngVien_Service service = new service.webservice.WsTlu30HoSoUngVien_Service();
        service.webservice.WsTlu30HoSoUngVien port = service.getWsTlu30HoSoUngVienPort();
        return port.tlu30HsuvInsert(createdBy, createdAt, isActive, maHoSo, ngayNhanHoSo, keHoachSo, boPhanDuTuyen, trinhDoVanHoa, hoTen, gioiTinh, cmdn, dienThoai, email, kinhNghiem, ghiChu, kemSoYeuLyLich, kemDonXinViec, kemGiayKhamSucKhoe, kemCmd, kemHoKhau, kemBangCap, giayToKhac);
    }

    private static Tlu30HoSoUngVien findById(int id) {
        service.webservice.WsTlu30HoSoUngVien_Service service = new service.webservice.WsTlu30HoSoUngVien_Service();
        service.webservice.WsTlu30HoSoUngVien port = service.getWsTlu30HoSoUngVienPort();
        return port.findById(id);
    }

    private static String tlu30HsuvUpdate(int id, java.lang.String createdBy, java.lang.String createdAt, boolean isActive, java.lang.String maHoSo, java.lang.String ngayNhanHoSo, java.lang.String keHoachSo, java.lang.String boPhanDuTuyen, java.lang.String trinhDoVanHoa, java.lang.String hoTen, java.lang.String gioiTinh, int cmdn, int dienThoai, java.lang.String email, java.lang.String kinhNghiem, java.lang.String ghiChu, java.lang.String kemSoYeuLyLich, java.lang.String kemDonXinViec, java.lang.String kemGiayKhamSucKhoe, java.lang.String kemCmd, java.lang.String kemHoKhau, java.lang.String kemBangCap, java.lang.String giayToKhac) throws ParseException_Exception {
        service.webservice.WsTlu30HoSoUngVien_Service service = new service.webservice.WsTlu30HoSoUngVien_Service();
        service.webservice.WsTlu30HoSoUngVien port = service.getWsTlu30HoSoUngVienPort();
        return port.tlu30HsuvUpdate(id, createdBy, createdAt, isActive, maHoSo, ngayNhanHoSo, keHoachSo, boPhanDuTuyen, trinhDoVanHoa, hoTen, gioiTinh, cmdn, dienThoai, email, kinhNghiem, ghiChu, kemSoYeuLyLich, kemDonXinViec, kemGiayKhamSucKhoe, kemCmd, kemHoKhau, kemBangCap, giayToKhac);
    }
}
